### ISSUE TITLE
RDotNet issue causing the software not working

### ISSUE THREAD

**Issue by huaqingw** [esftool/esftool#1]
Trying to use it today for spatial regression, but it says the following:

at RDotNet.REngine.Parse(String statement, StringBuilder incompleteStatement)
at RDotNet.REngine.<Defer>c__Iterator4.MoveNext()
at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source)
at RDotNet.REngine.Evaluate(String statement)
at ESFTool.frmRegression..ctor()

Please help.

**Comment by luoqiang-666** [comment]
I also encountered the same problem，have you solved this problem, thank you!

**Comment by huaqingw** [comment]
Hi, I switched to another computer and it is running well. I guess it is more related to some settings of the computer, instead of the software. Hope it helps. Thanks. 发件人: luoqiang-666发送时间: 2021年7月14日 6:32收件人: esftool/esftool抄送: huaqingw; Author主题: Re: [esftool/esftool] RDotNet issue causing the software not working (#1) I also encountered the same problem，have you solved this problem, thank you!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
